name: build-ubuntu

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: make
      run : make
    - name: make clean
      run : make clean
