name: build-ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libxrandr-dev

    - name: Checkout code
      uses: actions/checkout@v2
    - name: cmake
      run: cmake .
    - name: make
      run : make
    - name: make clean
      run : make clean
